version: '3'
services:
  nginx:
    image: registry.gitlab.com/ninjadotorg/constant-websites/nginx:${VERSION}
    ports:
    - '80:80'
  auth:
    image: registry.gitlab.com/ninjadotorg/constant-websites/auth:${VERSION}
    expose:
    - '3001'
  exchange:
    image: registry.gitlab.com/ninjadotorg/constant-websites/exchange:${VERSION}
    expose:
    - '3003'
  portal:
    image: registry.gitlab.com/ninjadotorg/constant-websites/portal:${VERSION}
    expose:
    - '3005'
  explorer:
    image: registry.gitlab.com/ninjadotorg/constant-websites/explorer:${VERSION}
    expose:
    - '3004'
